e:
 conf:
    authServer: http://oauth:9999/uaa
    loyAspect: false
    attachmentBaseDirectory : ./upload
    defaultLocale: zh_CN
    debugPageResult: false
    recordOperateLog: true
    ignoreJsonResponseUrls:
                         - /configuration/ui
                         - /swagger-resources
                         - /v2/api-docs
                         - /configuration/security
                         - /model/*/json
                         - /model/*/save
                         - /editor/stencilset
 
       
 apiInfo:
       title: E-框架 REST API
       description: 
       version: 2.0.0
       termsOfServiceUrl: 
       contact: 
            name: Loy Fu
            url: http://www.17jee.com
            email: 21549322@qq.com
       license: 
       licenseUrl: 
       pathsRegex: ^.*(?<!error)$
 
spring:
   application:
            name: log
   datasource: 
             #platform: mysql
             platform: h2
             #url: jdbc:mysql://db/e_log?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false
             url: jdbc:h2:tcp://db/~/.h2/e_log
             username: root
             password: 123456
             #driverClassName: com.mysql.jdbc.Driver
             driverClassName: org.h2.Driver
             max-active: 50
             max-idle: 40
             min-idle: 20
             initial-size: 6
             validation-query: select 1
             test-on-borrow: false
             test-on-return: false
             test-while-idle: true      
   jpa:
       properties: 
           hibernate:
             #dialect: com.loy.e.core.dialect.EMySQL5InnoDBDialect
             dialect: org.hibernate.dialect.H2Dialect
       showSql: false
       hibernate:
         ddlAuto: update
   jackson:
          date-format: yyyy-MM-dd HH:mm:ss
          
server:
    port: 28080
    tomcat:
      uri-encoding: UTF-8

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/ # 指定注册中心的地址
  instance:
    preferIpAddress: true

security:
  oauth2:
    client:
        accessTokenUri: ${e.conf.authServer}/oauth/token
        userAuthorizationUri: ${e.conf.authServer}/oauth/authorize
        clientId: acme
        clientSecret: acmesecret
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----
feign: 
  hystrix: 
    enabled: false    
                 
logging:
    path: ./logs
    file: ./logs/log.log

endpoints:
  actuator:
    enabled: true
  heapdump:
    enabled: false
  logfile:
    enabled: false
    path: /logfile
    sensitive: true
