e:
  conf: 
    loginSuccessUrl: http://localhost:8080/
server:
  port: 9999
  context-path: /uaa
security:
  oauth2:
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----
  user:
    password: password
spring:
   application:
            name: oauth
   datasource:
      platform: h2
      #url: jdbc:mysql://db/e_upm?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false
      url: jdbc:h2:tcp://db/~/.h2/e_upm
      username: root
      password: 123456
      #driverClassName: com.mysql.jdbc.Driver
      driverClassName: org.h2.Driver
      max-active: 50
      max-idle: 40
      min-idle: 20
      initial-size: 6
      validation-query: select 1
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
   jpa:
      properties:
        hibernate:
          #dialect: org.hibernate.dialect.MySQL5InnoDBDialect
          dialect: org.hibernate.dialect.H2Dialect
      showSql: false
      hibernate:
        ddlAuto: update
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/ # 指定注册中心的地址
  instance:
    preferIpAddress: true
                 
logging:
  path: ./logs
  file: ./logs/auth.log
